project:
  type: website
  output-dir: docs

website:
  title: "Guide emails accessibles et sobres"
  navbar:
    left:
      - href: index.qmd
        text: Accueil
      - about.qmd
      - introduction.qmd
      - partie-1.qmd
      - partie-2.qmd
      - references.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



