project:
  type: website
  output-dir: docs

bibliography: biblio.bib

format:
  html:
    theme: journal
    css: styles.css
    toc: true

website:
  title: "Guide e-mails inclusifs et éco-responsables"
  navbar:
    left:
      - href: index.qmd
        text: Accueil
      - href: introduction.qmd
        text: Pourquoi ?
      - href: partie-1.qmd
        text: Accessible
      - href: partie-2.qmd
        text: Éco-responsable
      - href: references.qmd
        text: Références et outils
      - href: about.qmd
        text: À propos





