project:
  type: website
  output-dir: docs

website:
  title: "Guide e-mails inclusifs et éco-responsables"
  navbar:
    left:
      - href: index.qmd
        text: Accueil
      - href: about.qmd
        text: A propos
      - href: introduction.qmd
        text: Introduction
      - href: partie-1.qmd
        text: Partie 1
      - href: partie-2.qmd
        text: Partie 2
      - href: references.qmd
        text: Références

format:
  html:
    theme: journal
    css: styles.css
    toc: true



