---
title: "Guide pour une communication par emails inclusive et éco-responsable"
---

Ce guide donne des recommandations pour adopter une communication par e-mail efficace, éco-responsable et accessible à toutes et à tous.  

La démarche de ce guide consiste à partir du particulier pour arriver au général : ce qui bénéficie aux personnes en situation de handicap bénéficie à tout le monde. En effet, adopter une communication par e-mails sobre et accessible apporte des gains :  

- En termes de temps et d’efficacité ; 
- Pour les personnes pas à l’aise avec l’outil informatique ; 
- En cas de matériel ou de service peu approprié à la lecture des e-mails (mauvaise connexion internet, usage du smartphone) ; 
- Pour les personnes en situation de handicap temporaire (par exemple : vous avez un bras dans le plâtre ou une infection à l’œil), et non temporaire. 

Cliquez sur "Pourquoi ?" <!-- ajouter lien vers page --> pour comprendre les enjeux de **l'accessibilité numérique** et de **l’empreinte environnementale du numérique**.

L'onglet "Accessible" <!-- ajouter lien vers cette page --> donne **6 conseils** pour envoyer des **e-mails inclusifs** et **accessibles** à **toutes et à tous**.

La "Partie 2 – Envoyer des e-mails éco-responsables" <!-- ajouter lien vers cette page --> détaille **4 usages** pour réduire l'impact environnemental de ses e-mails.

Toutes les **références** utilisées et des **outils supplémentaires** sont disponibles dans "Références et outils". <!-- ajouter lien vers page --> 

## Table des matières <!-- ajouter liens vers cette partie --> 
